---
image: mischief/docker-golang

env:
  - GOROOT=/usr/local/go
  - PATH=$GOROOT/bin:$PATH
  - GOPATH=/var/build/src
  - PATH=/var/build/bin:$PATH
  - REPO_DIR=$GOPATH/src/github.com/winston-ci/smith

script: |
  mkdir -p $(dirname $REPO_DIR)
  mv smith $REPO_DIR

  cd $REPO_DIR

  export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
  export PATH=${PWD}/Godeps/_workspace/bin:$PATH

  go install github.com/onsi/ginkgo/ginkgo

  ginkgo -r -nodes=4
